spring:
  data:
    redis:
      port: 6389
      host: 172.19.0.5

    mongodb:
      username: root
      password: root
      host: 172.19.0.4
      port: 27017
      database: chat
      authentication-database: admin

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: samcomo
    username: samcomo
    url: jdbc:mariadb://172.19.0.2:3306/samcomo

#     docker network =>   url: jdbc:mariadb://localhost:3308/samcomo
#     EC2 Mariadb => url: jdbc:mariadb://ec2-43-201-206-210.ap-northeast-2.compute.amazonaws.com:3308/samcomo

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: NulVADBtpXoUKTkzWFr+rCc5ckITa+A6uaLcZ9btLgg=

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: samcomo

fcm:
  key:
    path: firebase/firebase-adminsdk.json
    scope: https://www.googleapis.com/auth/cloud-platform
  api:
    url: https://fcm.googleapis.com/v1/projects/dbz24-d8690/messages:send
