spring:
  data:
    redis:
      host:
      password:

  datasource:
    url: jdbc:mariadb://localhost:3308/samcomo
    username: samcomo
    password: samcomo
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      instance-profile: true
      secret-key: # AWS S3 secret-key
      access-key: # AWS S3 access-key
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: samcomo

fcm:
  key:
    path: firebase/firebase-adminsdk.json
    scope: https://www.googleapis.com/auth/cloud-platform
  api:
    url: https://fcm.googleapis.com/v1/projects/${fcm-project-id}/messages:send