spring:
  data:
    redis:
      host:
      password:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: samcomo
    username: samcomo
    url: jdbc:mariadb://172.19.0.2:3306/samcomo

    # docker network =>   url: jdbc:mariadb://localhost:3308/samcomo
    # EC2 Mariadb => url: jdbc:mariadb://ec2-43-201-206-210.ap-northeast-2.compute.amazonaws.com:3308/samcomo
